// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBugosk6CZkt8sO5dX70K8dCaNB_4wLBXc',
    appId: '1:632553014957:web:ae56cb65935ed973cde824',
    messagingSenderId: '632553014957',
    projectId: 'psikolook-firebase',
    authDomain: 'psikolook-firebase.firebaseapp.com',
    storageBucket: 'psikolook-firebase.appspot.com',
    measurementId: 'G-78CG96Y8ZM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY08uhKeA5Tgcol4TLc80UCcLa7LXQ9hY',
    appId: '1:632553014957:android:de6adda6c4c0785fcde824',
    messagingSenderId: '632553014957',
    projectId: 'psikolook-firebase',
    storageBucket: 'psikolook-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqgxkD1j6aTGdwwM0UP5DMkp67-XpmwX8',
    appId: '1:632553014957:ios:0123c10fd8a58c34cde824',
    messagingSenderId: '632553014957',
    projectId: 'psikolook-firebase',
    storageBucket: 'psikolook-firebase.appspot.com',
    iosClientId: '632553014957-ehm0hfl7ots3sddbeundsncsvskcj13c.apps.googleusercontent.com',
    iosBundleId: 'com.example.psikolookAnasayfa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqgxkD1j6aTGdwwM0UP5DMkp67-XpmwX8',
    appId: '1:632553014957:ios:0123c10fd8a58c34cde824',
    messagingSenderId: '632553014957',
    projectId: 'psikolook-firebase',
    storageBucket: 'psikolook-firebase.appspot.com',
    iosClientId: '632553014957-ehm0hfl7ots3sddbeundsncsvskcj13c.apps.googleusercontent.com',
    iosBundleId: 'com.example.psikolookAnasayfa',
  );
}
